kari/Api/urls.py
from django.conf.urls import patterns, include, url
from Api import views

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^user/(?P<uid>\d+)/?$', views.userDetail ),
    url(r'^group/(?P<gid>\d+)/?$', views.groupDetail ),
    url(r'^login/?$', views.userLogin ),
    url(r'^contest/(?P<cid>\d+)/board/?$', views.boardDetail ),
)

kari/Cheat/urls.py
from django.conf.urls import patterns, include, url
from Cheat import views

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kari.views.home', name='home'),
    # url(r'^kari/', include('kari.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
	# url( r'^[Pp]roblem/', include( 'Problem.urls', namespace='Problem' )),
    #url(r'/goBack/$',views.goBack),
	url(r'^addrecord/(?P<cid>\d+)/$', views.addRecord, name='add_cheat_record'),
	url(r'^addrecord2/(?P<cid>\d+)/$', views.addRecord2, name='add_cheat_record_2'),
    url(r'^showresult/(?P<cid>\d+)/$', views.showResult, name='show_cheat_result'),
    url(r'^showresult/(?P<cid>\d+)/page/(?P<page>\d+)/$', views.showResult, name='show_cheat_result'),
    # url(r'^showresult/(?P<sid_a>\d+)/(?P<sid_b>\d+)/$', views.showCodeDiff, name='show_code_diff'),
    url(r'^codediff/(?P<ct_id>\d+)/$', views.showCodeDiff, name='show_code_diff'),
)

kari/Contest/urls.py
from django.conf.urls import patterns, url
from Contest import views

urlpatterns = patterns('',
        url(r'^$', views.listContestByUser, name='list_available_contests'),
        url(r'^page/(?P<pageId>\d+)/$', views.listContestByUser, name='list_user_contest'),
        url(r'^manage/$', views.listContestByUserAndPriv, name='list_user_contest_manage'),
        url(r'^manage/page/(?P<pageId>\d+)/$', views.listContestByUserAndPriv, name='list_user_contest_manage'),
        url(r'^myself/$', views.listContestByAuthor, name='list_user_contest_myself'),
        url(r'^myself/page/(?P<pageId>\d+)/$', views.listContestByAuthor, name='list_user_contest_myself'),
        url(r'^courseclass/(?P<ccId>\d+)/$', views.listContest, name='list_contest'),
        url(r'^courseclass/(?P<ccId>\d+)/page/(?P<pageId>\d+)/$', views.listContest, name='list_contest'),
        url(r'^manage/courseclass/(?P<ccId>\d+)/$', views.listContestByPriv, name='list_contest_manage'),
        url(r'^manage/courseclass/(?P<ccId>\d+)/page/(?P<pageId>\d+)/$', views.listContestByPriv, name='list_contest_manage'),
        url(r'^(?P<cId>\d+)/$', views.showContest, name='show_contest'),
        url(r'^add/$', views.chooseCourseClass, name='add_contest_choose'), 
        url(r'^add/courseclass/(?P<ccId>\d+)/$', views.addContest, name='add_contest'), 
        url(r'^update/(?P<cId>\d+)/$', views.updateContest, name='update_contest'), 
        url(r'^release_board/(?P<cId>\d+)/$', views.releaseBoardTime, name='release_board'), 
        url(r'^notice/contest/(?P<cId>\d+)/$', views.listContestNotice, name='list_contest_notice'),
        url(r'^(?P<cId>\d+)/notice/(?P<cnId>\d+)/$', views.showContestNotice, name='show_contest_notice'), 
        url(r'^notice/add/contest/(?P<cId>\d+)/$', views.addContestNotice, name='add_contest_notice'), 
        url(r'^notice/update/(?P<cnId>\d+)/contest/(?P<cId>\d+)/$', views.updateContestNotice, name='update_contest_notice'), 
        url(r'^getContestNoticeList/$', views.getContestNoticeList, name='get_contest_notice_list'),

        url(r'^clarifications/(?P<cid>\d+)/$', views.viewAllClarifications, name='view_all_clars'),
        url(r'^clarifications/add/(?P<cid>\d+)/$', views.addClarification, name='add_clar'),
        url(r'^clarifications/answer/(?P<clar_id>\d+)/$', views.answerClarification, name='answer_clar'),
        url(r'^clarifications/delete/(?P<clar_id>\d+)/$', views.deleteClarification, name='delete_clar'),
        url(r'^all/$', views.listContestByUserAll, name='list_all_contests'),

        #url(r'^contestself$', views.listContestByUserSelf),
        )

kari/Problem/urls.py
from django.conf.urls import patterns, url
from Problem import views

urlpatterns = patterns('',
        url(r'^list/(\d+)/$', views.listProblem, name='list'),
        url(r'^list/$', views.listProblem, name='list'),
        url(r'^manage/$', views.listManageProblem, name='manage'),
        url(r'^manage/(?P<pageId>\d+)/$', views.listManageProblem, name='manage'),
        #url(r'^listManager/(\d+)/$', views.listManageProblem, name='listmanager'),
        #url(r'^listManager/$', views.listManageProblem, name='listmanager'),
        url(r'^p/(\d+)/$', views.showProblem, name='problem'),

        url(r'^contest/(?P<c_id>\d+)/problem/(?P<idx>[A-Z])/$',views.showContestProblem, name="contest_problem"), 

        url(r'^addProblem/$',views.chooseCourse, name='addproblem_choosecs'),
        url(r'^addProblem/(\d+)/$',views.addProblem, name='addproblem'),
        url(r'^addProblemSubmit',views.addProblemSubmit, name='addcommit'),
        url(r'^updateProblem/(\d+)/$', views.updateProblem, name='updateproblem'),
        url(r'^deleteProblem/(?P<problem_id>\d+)/$', views.deleteProblem, name='deleteproblem'),
        url(r'^updateProblemSubmit/(\d+)/$',views.updateProblemSubmit, name='updatecommit'),
        url(r'^getProblemTitle/$', views.getProblemTitle, name='title'),
        #        url(r'^addData/$', views.addData),
        #        url(r'^updateData/(\d+)/$', views.updateData),
        #url(r'^test/$',views.testPage),
        url(r'^addProblem/upload$',views.testUpload, name='upload'),
        url(r'^testUploadSubmit/$',views.testUploadSubmit, name='testups'),
        url(r'^testdata/(?P<problem_id>\d+)/(?P<case_id>\d+)/(?P<mode>\d+)/$', views.previewTestData, name = 'previewtestdata'),
        )

kari/Submission/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
from Submission import views, general_views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kari.views.home', name='home'),
    # url(r'^kari/', include('kari.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url( r'^$', views.index, name='index'),
    url( r'^(?i)index/$', views.index, name='index'),
    # url( r'^(?i)all/(\d+)/$', views.submissionList, name='all'),
    # url( r'^(?i)all/$', views.submissionList, name='all'),
    # url( r'^(?i)status/$', views.submissionList, name='status'),
    url( r'^(?i)rejudge/in_contest/(?P<sid>\d+)/$', views.rejudgeSubmission, name='contest_rejudge'),
    url( r'^(?i)status/$', general_views.generalSubmissionList, name='status'),
    url( r'^(?i)status/page/(?P<page_id>\d+)/$', general_views.generalSubmissionList, name='status'),
    url( r'^(?i)submit/(?P<problem_id>\d+)/$', general_views.addGeneralSubmission, name='general_submit'),
    url( r'^(?i)submit/$', general_views.addGeneralSubmission, name='general_submit'),
    url( r'^(?i)detail/(?P<gsid>\d+)/$', general_views.viewCodeAndInfo, name='general_code_and_info'),
    url( r'^(?i)rejudge/(\d+)/$', general_views.rejudgeGeneralSubmission, name='general_rejudge'),

    url( r'^status/contest/(?P<contest_id>\d+)/$', views.submissionList, name='contest_status'), # modified
    url( r'^status/contest/(?P<contest_id>\d+)/page/(?P<page_id>\d+)/$', views.submissionList, name='contest_status'), # modified
    url( r'^(?i)submit/contest/(?P<contest_id>\d+)/problem/(?P<problem_index>([A-Z]))/$', views.addSubmission, name='submit'), # modified
    url( r'^(?i)detail/in_contest/(\d+)/$', views.viewCodeAndInfo, name='code_and_info'),
)

kari/User/urls.py
from django.conf.urls import patterns, url
from User import views

urlpatterns = patterns('',
    url(r'^$', views.showUserInfo, name='showinfo'),
    url(r'^update/$', views.update, name='update'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^add/student/$', views.addMultiUser, name='addstudent'),
    url(r'^add/admin/$', views.addAdmin, name='addadmin'),
    url(r'^add/school/$', views.addSchool, name='addschool'),
    url(r'^add/group/$', views.addGroup, name='addgroup'),
    url(r'^viewuser/(?P<uid>\d+)/$', views.viewUserInfo, name='viewuser'),
    url(r'^reset/(?P<uid>\d+)$', views.ResetPasswd, name='reset'),
    url(r'^school/(?P<school_id>\d+)/$', views.showSchool, name='show_school'),
    url(r'^school/(?P<school_id>\d+)/page/(?P<page_id>\d+)/$', views.showSchool, name='show_school'),
    url(r'^manage/admin/$', views.listAdmin, name='manageadmin'),
    url(r'^manage/student/$', views.listStudent, name='managestudent'),
    url(r'^manage/student2/$', views.listStudent2, name='managestudent'),
    url(r'^manage/student/page/(?P<page_id>\d+)/$', views.listStudent, name='managestudent'),
    url(r'^manage/student/page/(?P<page_id>\d+)/$', views.listStudent2, name='managestudent'),
    url(r'^manage/school/$', views.manageSchool, name='manageschool'),
    url(r'^manage/group/$', views.manageGroup, name='managegroup'),
    url(r'^manage/group/page/(?P<pageId>\d+)/$', views.manageGroup, name='managegroup'),
   
    url(r'^modify/school/(?P<school_id>\d+)$', views.modifySchool, name='modifyschool'),
    url(r'^modify/group/(?P<group_id>\d+)$', views.modifyGroup, name='modifygroup'),
    url(r'^modify/group/(?P<group_id>\d+)/resetall/$', views.resetGroupMemberPasswdHomepage, name='resetgrouphomepage'),
    url(r'^modify/group/(?P<group_id>\d+)/resetall/(?P<mode>[a-z]+)$', views.resetGroupMemberPasswd, name='resetgroup'),
    url(r'^modify/group/(?P<group_id>\d+)/delmember/(?P<user_id>\d+)$', views.delMember, name='delgroupmember'),
    url(r'^modify/group/(?P<group_id>\d+)/addmember/$', views.addMember, name='addgroupmember'),
    url(r'^download/(?P<usname>.+)/$',views.csvDownload,name='csvdownload'),
)

kari/kari/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kari.views.home', name='home'),
    # url(r'^kari/', include('kari.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

    #common url
    url( r'^$', 'common.views.index', name='index'),
    url( r'^login/$', 'common.views.login', name='login'),
    url( r'^logout/$', 'common.views.logout', name='logout'),
    url( r'^test/$', 'common.views.test', name='test'),
    url( r'^faq/$', 'common.views.faq', name='faq'),
    url( r'^whitepaper/$', 'common.views.whitepaper', name='whitepaper'),
    url( r'^abouttemp/$', 'common.views.about', name='about'),
    url( r'^register/$', 'common.views.register', name='register'),

    url( r'^contest/', include( 'Contest.urls', namespace='Contest')),
    url( r'^submission/', include( 'Submission.urls', namespace='Submission')),
    #url( r'^submission2/', include( 'Submission2.urls', namespace='Submission2')),
    url( r'^course/', include( 'Course.urls', namespace='Course')),
    url( r'^user/', include( 'User.urls', namespace='User')),
    url( r'^problem/', include( 'Problem.urls', namespace='Problem' )),
    url( r'^statistic/', include( 'Statistic.urls', namespace='Statistic' )),
    #url( r'^statistic2/', include( 'Statistic2.urls', namespace='Statistic2' )),
    url( r'^cheat/', include( 'Cheat.urls', namespace='Cheat' )),

    #url( r'^fresh/', include( 'Fresh.urls', namespace = 'Fresh')),    
    url( r'^apply/', include( 'Register.urls', namespace = 'Register')),    
    url( r'^ckeditor/', include('ckeditor.urls')),

    url( r'^print/', include('Print.urls')),

    url( r'^api/', include('Api.urls')),
)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/',include(debug_toolbar.urls)),
    )

kari/Cheat/forms.py
# -*- coding: utf-8 -*-
from django import forms

class ChooseProbForm(forms.Form):
    def __init__(self, cp, *args, **kwargs):
        super(ChooseProbForm, self).__init__(*args, **kwargs)
        self.fields['contest_problem'] = forms.ModelMultipleChoiceField(
                label=u'题目选择',
                queryset = cp,
                widget = forms.CheckboxSelectMultiple,
                )

kari/templates/newtpl/cheat/addRecord.html
{%extends "newtpl/admin.html" %}
{%block title%}代码查重题目选择{%endblock%}
{%block page-header%}
<h1>代码查重题目选择 <small>{{contest.contest_title}}</small></h1>
{%endblock page-header%}
{%block admin-access%}
<a class="btn btn-primary btn-block" href="{%url 'Contest:show_contest' contest.cid%}">&laquo;返回测验</a>
{%endblock%}
{%block admin-form%}
<form ID="res" class="form-horizontal" onsubmit="postRequest(); return false;">
    {%csrf_token%}
    <fieldset>
        <div class="control-group">
            <label class="control-label">题目选择</label>
            {{form.contest_problem.errors}}
            <div class="controls">
                {{form.contest_problem}}
            </div>
        </div>
    </fieldset>
    <div class="form-actions">
        <input id="submit" class="btn btn-primary" type="submit" value="查看结果">
        <input class="btn" type="reset" value="重置">
    </div>
</form>
<script type="text/javascript">
    function postRequest() {
        document.querySelector('#submit').disabled = true;
        alert("完成查重后将自动跳转，请耐心等待...");
        $.ajax({
            type: "POST",
            url: "{%url 'Cheat:add_cheat_record' contest.cid%}",
            data: $('#res').serialize(),
            success: function() {
                window.location.href = "{%url 'Cheat:show_cheat_result' contest.cid%}";
            },
            timeout: function() { $.ajax(this); }
        });
    }
</script>
{%endblock admin-form%}

kari/templates/newtpl/cheat/code_diff.html
{% extends "newtpl/base.html" %}

{% block title %} 查重对比 {{ sub_a.sid }}-{{ sub_b.sid }}. - kAri Online Judge{% endblock %}
{% block main-left %}

<h1>代码查重分析</h1>
<h3>代码相似度: {{ct_obj.ratio|floatformat:2}}%</h3>

<div class="container-fluid">
<div class="row-fluid">
    {% block code_a %}
        <div class="span6">
            <table class="table">
                <tbody>
                    <tr>
                        <td>提交编号</td>
                        <td><a href="{% url 'Submission:code_and_info' sub_a.sid %}">{{ sub_a.sid }}</a></td>
                    </tr>
                    <tr>
                        <td>用户</td>
                        <td><a href="{% url 'User:viewuser' sub_a.user.uid %}">{{ sub_a.user.username }}</a></td>
                    </tr>
                    <tr>
                        <td>IP地址</td>
                        <td>{{ ip_a }}</td>
                    </tr>
                </tbody>
            </table>
            <pre class="prettyprint">{{ code_a }}</pre>
    </div>
    {% endblock code_a %}

    {% block code_b %}
        <div class="span6">
            <table class="table">
                <tbody>
                    <tr>
                        <td>提交编号</td>
                        <td><a href="{% url 'Submission:code_and_info' sub_b.sid %}">{{ sub_b.sid }}</a></td>
                    </tr>
                    <tr>
                        <td>用户</td>
                        <td><a href="{% url 'User:viewuser' sub_b.user.uid %}">{{ sub_b.user.username}}</a></td>
                    </tr>
                    <tr>
                        <td>IP地址</td>
                        <td>{{ ip_b }}</td>
                    </tr>

                </tbody>
            </table>
            <pre class="prettyprint">{{ code_b }}</pre>
        </div>
    {% endblock code_b %}

    </div>
</div>

{% endblock %}

{% comment %}
{% with c=submission.problem_index.contest %}
<div class="well">
    <a class="btn btn-info btn-block" href="{% url 'Submission:contest_status' c.cid %}{{ status_query }}">结果列表</a>
    <a class="btn btn-block" href={%url 'Contest:show_contest' c.cid%}>&laquo;返回测验首页</a>
</div>
{% endwith %}
{% endcomment %}

{%block ext-script%}
<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
{#<script src="/static/js/google-code-prettify/run_prettify.js"></script>#}
{%endblock%}

kari/templates/newtpl/cheat/showResult.html
{%extends "newtpl/admin.html" %}
{%block title%}代码查重结果{%endblock%}
{%block page-header%}
<h1>代码查重结果 <small>{{contest.contest_title}}</small></h1>
{%endblock page-header%}
{%block admin-access%}
<a class="btn btn-primary btn-block" href="{%url 'Contest:show_contest' contest.cid%}">&laquo;返回测验</a>
{%endblock%}
{%block admin-form%}
{%if cheat_list and cheat_list.paginator.num_pages > 1%}
<div class="pagination pagination-centered">
<ul>
    {% if cheat_list.has_previous %}
    <li><a href="{%url 'Cheat:show_cheat_result' contest.cid cheat_list.previous_page_number%}{%if request.GET.items%}?{%for k,v in request.GET.items%}{{k}}={{v}}&{%endfor%}{%endif%}">&laquo;</a></li>
    {% else %}
    <li class="disabled"><a href="#">&laquo;</a></li>
    {% endif %}

    <li class="disabled"><a href="#">{{ cheat_list.number }}</a></li>
    
    {% if cheat_list.has_next %}
    <li><a href="{% url 'Cheat:show_cheat_result' contest.cid cheat_list.next_page_number %}{%if request.GET.items%}?{%for k,v in request.GET.items%}{{k}}={{v}}&{%endfor%}{%endif%}">&raquo;</a></li>
    {% else %}
    <li class="disabled"><a href="#">&raquo;</a></li>
    {% endif %}
</ul>
<p>共{{cheat_list.paginator.num_pages}}页</p>
</div>
{%endif%}
<div>

<form class="form-inline kari-form-inline" method="get">
    {{form.problem_index}}
    {{form.username}}
    <input class="btn btn-primary" type="submit" value="筛选">
</form>

<table class="table table-bordered table-striped table-hover">
    <thead>
        <th>题目</th>
        <th>用户1</th>
        <th>提交ID</th>
        <th>用户2</th>
        <th>提交ID</th>
        <th>状态</th>
        <th>相似度</th>
    </thead>
    {%for ct in cheat_list %}
    <tr>
        <td><a target="_blank" href="{%url 'Problem:contest_problem' contest.cid ct.contest_problem.problem_index%}">{{ct.contest_problem.problem_index}}</a></td>
        <td>{{ct.sub1.user.username}}</td>
        {%comment%}<td><a target="_blank" href="{% url 'Submission:code_and_info' ct.sub1.sid %}">{{ct.sub1.sid}}</a></td>{%endcomment%}
        <td><a target="_blank" href="{% url 'Submission:code_and_info' ct.sub1.sid %}">{{ct.sub1.sid}}</a></td>
        <td>{{ct.sub2.user.username}}</td>
        <td><a target="_blank" href="{% url 'Submission:code_and_info' ct.sub2.sid %}">{{ct.sub2.sid}}</a></td>
        <td>{%if ct.status == -1%}待检查{%elif ct.status == 0%}检查中{%else%}完毕{%endif%}</td>
        <td><a href="{% url 'Cheat:show_code_diff' ct.ctid %}" target="blank" >{{ct.ratio|floatformat:2}}</a></td>
    </tr>
    {%endfor%}
</table>
</div>
{%endblock admin-form%}