kari/Api/urls.py
from django.conf.urls import patterns, include, url
from Api import views

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^user/(?P<uid>\d+)/?$', views.userDetail ),
    url(r'^group/(?P<gid>\d+)/?$', views.groupDetail ),
    url(r'^login/?$', views.userLogin ),
    url(r'^contest/(?P<cid>\d+)/board/?$', views.boardDetail ),
)

kari/Contest/urls.py
from django.conf.urls import patterns, url
from Contest import views

urlpatterns = patterns('',
        url(r'^$', views.listContestByUser, name='list_available_contests'),
        url(r'^page/(?P<pageId>\d+)/$', views.listContestByUser, name='list_user_contest'),
        url(r'^manage/$', views.listContestByUserAndPriv, name='list_user_contest_manage'),
        url(r'^manage/page/(?P<pageId>\d+)/$', views.listContestByUserAndPriv, name='list_user_contest_manage'),
        url(r'^myself/$', views.listContestByAuthor, name='list_user_contest_myself'),
        url(r'^myself/page/(?P<pageId>\d+)/$', views.listContestByAuthor, name='list_user_contest_myself'),
        url(r'^courseclass/(?P<ccId>\d+)/$', views.listContest, name='list_contest'),
        url(r'^courseclass/(?P<ccId>\d+)/page/(?P<pageId>\d+)/$', views.listContest, name='list_contest'),
        url(r'^manage/courseclass/(?P<ccId>\d+)/$', views.listContestByPriv, name='list_contest_manage'),
        url(r'^manage/courseclass/(?P<ccId>\d+)/page/(?P<pageId>\d+)/$', views.listContestByPriv, name='list_contest_manage'),
        url(r'^(?P<cId>\d+)/$', views.showContest, name='show_contest'),
        url(r'^add/$', views.chooseCourseClass, name='add_contest_choose'), 
        url(r'^add/courseclass/(?P<ccId>\d+)/$', views.addContest, name='add_contest'), 
        url(r'^update/(?P<cId>\d+)/$', views.updateContest, name='update_contest'), 
        url(r'^release_board/(?P<cId>\d+)/$', views.releaseBoardTime, name='release_board'), 
        url(r'^notice/contest/(?P<cId>\d+)/$', views.listContestNotice, name='list_contest_notice'),
        url(r'^(?P<cId>\d+)/notice/(?P<cnId>\d+)/$', views.showContestNotice, name='show_contest_notice'), 
        url(r'^notice/add/contest/(?P<cId>\d+)/$', views.addContestNotice, name='add_contest_notice'), 
        url(r'^notice/update/(?P<cnId>\d+)/contest/(?P<cId>\d+)/$', views.updateContestNotice, name='update_contest_notice'), 
        url(r'^getContestNoticeList/$', views.getContestNoticeList, name='get_contest_notice_list'),

        url(r'^clarifications/(?P<cid>\d+)/$', views.viewAllClarifications, name='view_all_clars'),
        url(r'^clarifications/add/(?P<cid>\d+)/$', views.addClarification, name='add_clar'),
        url(r'^clarifications/answer/(?P<clar_id>\d+)/$', views.answerClarification, name='answer_clar'),
        url(r'^clarifications/delete/(?P<clar_id>\d+)/$', views.deleteClarification, name='delete_clar'),
        url(r'^all/$', views.listContestByUserAll, name='list_all_contests'),

        #url(r'^contestself$', views.listContestByUserSelf),
        )

kari/Course/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
from Course import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kari.views.home', name='home'),
    # url(r'^kari/', include('kari.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    #url( r'^$', views.index, name='index'),
    #url( r'^index/$', views.index, name='index'),
    url( r'^(?P<course_id>\d+)/$', views.showCourse, name='showCourse'),
    url( r'^add/$', views.addCourse, name='addCourse'),
    url( r'^add/school/(?P<school_id>\d+)/$', views.addCourse, name='addCourse'),
    url( r'^update/(?P<course_id>\d+)/$', views.updateCourse, name='updateCourse'),
    # url( r'^delete/(?P<course_id>\d+)/$', views.deleteCourse, name='deleteCourse'),
    url( r'^setadmin/c/(?P<course_id>\d+)/$', views.setCourseAdmin, name='setCourseAdmin'),

    url( r'^list/school/(?P<school_id>\d+)/$', views.courseList, name='listCourse'),

    url( r'^courses/$', views.courseList, name='courses'),
    url( r'^courses/page/(?P<page_id>\d+)/$', views.courseList, name='courses'),
    url( r'^(?P<course_id>\d+)/problems/$', views.showCourseProblems, name='courseProblems'),
    url( r'^(?P<course_id>\d+)/problems/page/(?P<page_id>\d+)/$', views.showCourseProblems, name='courseProblems'),
    url( r'^(?P<course_id>\d+)/classes/$', views.showCourseClasses, name='courseClasses'),
    url( r'^(?P<course_id>\d+)/classes/page/(?P<page_id>\d+)/$', views.showCourseClasses, name='courseClasses'),

    url( r'^class/(?P<course_class_id>\d+)/$', views.showCourseClass, name='showCourseClass'),
    url( r'^class/add/$', views.addCourseClass, name='addCourseClass'),
    url( r'^class/add/course/(?P<course_id>\d+)/$', views.addCourseClass, name='addCourseClass'),
    url( r'^class/update/(?P<course_class_id>\d+)/$', views.updateCourseClass, name='updateCourseClass'),
    # url( r'^class/delete/(?P<course_class_id>\d+)/$', views.deleteCourseClass, name='deleteCourseClass'),
    url( r'^setadmin/cc/(?P<course_class_id>\d+)/$', views.setCourseClassAdmin, name='setCourseClassAdmin'),
    # url( r'^classes/course/(?P<course_id>\d+)/$', views.courseClassList, name='listCourseClass'),

    url( r'^classes/$', views.courseClassList, name='classes'),
    url( r'^classes/page/(?P<page_id>\d+)/$', views.courseClassList, name='classes'),
    url( r'^class/(?P<course_class_id>\d+)/groups/add/(?P<group_id>\d+)/$', views.addGroup, name='addGroup'),
    url( r'^class/(?P<course_class_id>\d+)/groups/add/$', views.addGroup, name='addGroup'),
    url( r'^class/(?P<course_class_id>\d+)/groups/$', views.showCourseClassGroups, name='groups'),
    url( r'^class/(?P<course_class_id>\d+)/contests/$', views.showCourseClassContests, name='showCourseClassContests'),
    url( r'^class/(?P<course_class_id>\d+)/students/$', views.showCourseClassStudents, name='students'),
    url( r'^class/(?P<course_class_id>\d+)/problems/$', views.showCourseClassProblems, name='showCourseClassProblems'),

    url( r'^class/(?P<course_class_id>\d+)/groups/page/(?P<page_id>\d+)/$', views.showCourseClassGroups, name='groups'),
    url( r'^class/(?P<course_class_id>\d+)/contests/page/(?P<page_id>\d+)/$', views.showCourseClassContests, name='showCourseClassContests'),
    url( r'^class/(?P<course_class_id>\d+)/students/page/(?P<page_id>\d+)/$', views.showCourseClassStudents, name='students'),
    url( r'^class/(?P<course_class_id>\d+)/problems/page/(?P<page_id>\d+)/$', views.showCourseClassProblems, name='showCourseClassProblems'),
)

kari/Print/urls.py
from django.conf.urls import patterns, include, url
from Print import views

urlpatterns = patterns('',
    url( r'^$', views.submit, name='submit'),
)

kari/Problem/urls.py
from django.conf.urls import patterns, url
from Problem import views

urlpatterns = patterns('',
        url(r'^list/(\d+)/$', views.listProblem, name='list'),
        url(r'^list/$', views.listProblem, name='list'),
        url(r'^manage/$', views.listManageProblem, name='manage'),
        url(r'^manage/(?P<pageId>\d+)/$', views.listManageProblem, name='manage'),
        #url(r'^listManager/(\d+)/$', views.listManageProblem, name='listmanager'),
        #url(r'^listManager/$', views.listManageProblem, name='listmanager'),
        url(r'^p/(\d+)/$', views.showProblem, name='problem'),

        url(r'^contest/(?P<c_id>\d+)/problem/(?P<idx>[A-Z])/$',views.showContestProblem, name="contest_problem"), 

        url(r'^addProblem/$',views.chooseCourse, name='addproblem_choosecs'),
        url(r'^addProblem/(\d+)/$',views.addProblem, name='addproblem'),
        url(r'^addProblemSubmit',views.addProblemSubmit, name='addcommit'),
        url(r'^updateProblem/(\d+)/$', views.updateProblem, name='updateproblem'),
        url(r'^deleteProblem/(?P<problem_id>\d+)/$', views.deleteProblem, name='deleteproblem'),
        url(r'^updateProblemSubmit/(\d+)/$',views.updateProblemSubmit, name='updatecommit'),
        url(r'^getProblemTitle/$', views.getProblemTitle, name='title'),
        #        url(r'^addData/$', views.addData),
        #        url(r'^updateData/(\d+)/$', views.updateData),
        #url(r'^test/$',views.testPage),
        url(r'^addProblem/upload$',views.testUpload, name='upload'),
        url(r'^testUploadSubmit/$',views.testUploadSubmit, name='testups'),
        url(r'^testdata/(?P<problem_id>\d+)/(?P<case_id>\d+)/(?P<mode>\d+)/$', views.previewTestData, name = 'previewtestdata'),
        )

kari/kari/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kari.views.home', name='home'),
    # url(r'^kari/', include('kari.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

    #common url
    url( r'^$', 'common.views.index', name='index'),
    url( r'^login/$', 'common.views.login', name='login'),
    url( r'^logout/$', 'common.views.logout', name='logout'),
    url( r'^test/$', 'common.views.test', name='test'),
    url( r'^faq/$', 'common.views.faq', name='faq'),
    url( r'^whitepaper/$', 'common.views.whitepaper', name='whitepaper'),
    url( r'^abouttemp/$', 'common.views.about', name='about'),
    url( r'^register/$', 'common.views.register', name='register'),

    url( r'^contest/', include( 'Contest.urls', namespace='Contest')),
    url( r'^submission/', include( 'Submission.urls', namespace='Submission')),
    #url( r'^submission2/', include( 'Submission2.urls', namespace='Submission2')),
    url( r'^course/', include( 'Course.urls', namespace='Course')),
    url( r'^user/', include( 'User.urls', namespace='User')),
    url( r'^problem/', include( 'Problem.urls', namespace='Problem' )),
    url( r'^statistic/', include( 'Statistic.urls', namespace='Statistic' )),
    #url( r'^statistic2/', include( 'Statistic2.urls', namespace='Statistic2' )),
    url( r'^cheat/', include( 'Cheat.urls', namespace='Cheat' )),

    #url( r'^fresh/', include( 'Fresh.urls', namespace = 'Fresh')),    
    url( r'^apply/', include( 'Register.urls', namespace = 'Register')),    
    url( r'^ckeditor/', include('ckeditor.urls')),

    url( r'^print/', include('Print.urls')),

    url( r'^api/', include('Api.urls')),
)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/',include(debug_toolbar.urls)),
    )

kari/Problem/forms.py
# -*- coding: utf-8 -*-

from django import forms
from ckeditor.widgets import CKEditorWidget

class addProblemForm(forms.Form):
    PROB_PRIV_CH = (
            ('private','只有自己可见'),  #only the author may view and modify it outside the contest
            ('protected','所有教师可见'),  #the admin with the same root as the author may view and modify it
            ('public','公开'),  #the admin with the same root as the author may view and modify it, with all user may view it outside
            #('ext','ext'),  #more complex privilege
            #if more complex privilege needed, you may add it here
            )
    SPJ_CH = (
            ('0', u'否'),
            ('1', u'是'),
            )

    prob_title = forms.CharField(max_length=128, initial='Untitled', label=u'题目标题')
    prob_priv = forms.ChoiceField(choices=PROB_PRIV_CH, label=u'题目权限')
    prob_time = forms.IntegerField(initial=1000, label=u'时间限制 (ms)')
    prob_memory = forms.IntegerField(initial=65536, label=u'内存限制 (kb)', max_value=1073741824)
    prob_codelength = forms.IntegerField(initial=65536, label=u'代码长度限制 (b)')
    prob_desc = forms.CharField(widget=CKEditorWidget(), label=u'题目描述' )
    prob_input_desc = forms.CharField(widget=CKEditorWidget(), label=u'输入描述')
    prob_output_desc = forms.CharField(widget=CKEditorWidget(), label=u'输出描述')
##    prob_desc = forms.CharField(widget=forms.Textarea(attrs={'class':'ckeditor'}), label=u'题目描述' )
##    prob_input_desc = forms.CharField(widget=forms.Textarea(attrs={'class':'ckeditor'}), label=u'输入描述')
##    prob_output_desc = forms.CharField(widget=forms.Textarea(attrs={'class':'ckeditor'}), label=u'输出描述')
    prob_input_sample = forms.CharField(widget=forms.Textarea, label=u'输入样例')
    prob_output_sample = forms.CharField(widget=forms.Textarea, label=u'输出样例')
    is_spj = forms.ChoiceField(choices=SPJ_CH, label=u'是否需要Special Judge')
    change_data = forms.ChoiceField(initial='1', choices=SPJ_CH, label=u'是否需要修改数据')
    #course_id = forms.IntegerField( label=u'课程')
#    file_in = forms.FileField(label=u'上传输入数据')
#    file_out = forms.FileField(label=u'上传输出数据')

#class uploadDataForm(form.Form):

kari/templates/Problem/Problem.html
{% extends "base.html" %}

{% block title %} 题目详情 {{ p.pid }} {% endblock %}

{% block main-left %}

{% if contest %}
<p><a href="{% url 'Contest:show_contest' contest.cid %}">题目列表</a></p>
<script> var cid = {{ contest.cid }} </script>
<script src="/static/js/contest.js"></script>    
<b> 考试公告：</b>
<marquee id="contest_notice"  onmouseover="stop();"  onmouseout="start();"></marquee>
<h2> {{ contest.title }} </h2>
<p> {{ contest.now }} {{ contest.start_time }} {{ contest.status }} {{ contest.left }} </p>

{% else %}
<p><a href="{% url 'Problem:list' p.pid %}">Problem List</a></p>
{% endif %}

<h> {{ p.prob_title }} </h>
<p> 通过次数:  提交次数:  </p><br/>
<p> 时间限制: {{ p.prob_time }} 毫秒 内存限制: {{ p.prob_memory }} kb</p><br/>
{% if p.is_spj %}
<p><strong> Special Judge </strong></p><br/>
{% endif %}

<br/>
<p>题目描述:</p>
<p> {{ prob_desc}} </p><br/>
<p>输入描述:</p>
<p> {{ prob_input_desc}} </p><br/>
<p>输出描述:</p>
<p> {{ prob_output_desc}} </p><br/>
<p>输入样例:</p>
<p> {{ prob_input_sample}} </p><br/>
<p>输出样例:</p>
<p> {{ prob_output_sample}} </p><br/>
<br/>
{% if contest %}
<a href="{% url 'Submission:submit' contest.cid idx %}">提交代码</a> <a href='#'>统计信息</a><br/>
{% else %}
<a href="{#% url 'Submission:submit' %#}">提交代码</a> <a href='#'>统计信息</a><br/>
{% endif %}

{% endblock %}

{% block main-right %}

{% if contest %}<p><a href="{% url 'Contest:show_contest' contest.cid %}"> 返回考试</a></p>{% endif %}
{% if p.course.id %}<p><a href="{% url 'Course:showCourse' p.course.id %}"> 返回所属课程</a></p>{% endif %}
{% endblock %}

kari/templates/Problem/addData.html
{% extends "base.html" %}

{% block title %} 添加题目 {% endblock %}

{% block main-left %}
<script src="/static/js/problem.js"></script>
<form action="/Problem/addData" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table table-bordered">
        {{ form.as_table }}
    </table>
    <tbody>
        {% for d in  %}
    </tbody>
    <input type="submit" value="提交">
</form>
{% endblock %}

{% block main-right %}
{% endblock %}

kari/templates/Problem/addProblem.html
{% extends "base.html" %}

{% block title %} 添加题目 {% endblock %}

{% block main-left %}
<script src="/static/js/problem.js"></script>
<script src="/static/ckeditor/ckeditor.js"></script>
<form action="{% url 'Problem:addcommit' %}" method="POST" enctype="multipart/form-data" onSubmit="return checkAllData()">
    {% csrf_token %}
    <table class="table table-bordered">
        {{ form.as_table }}
    </table>
    <table class="table table-bordered" id="data_table">
        <tr>
            <th width="10%" class="data_modifiy">
                <button type="button" onclick="addData()">添加</button>
            </th>
            <th width="40%" class="data_in">输入数据文件
            </th>
            <th width="40%" class="data_out">输出数据文件
            </th>
            <th width="10%" class="data_scr">数据得分
            </th>
        </tr>
    </table>
    <input type="submit" value="提交">
</form>
{% endblock %}

{% block main-right %}
{% endblock %}

kari/templates/Problem/old_addProblem.html
{% extends "base.html" %}

{% block title %} 添加题目 {% endblock %}

{% block main-left %}

<form action="/Problem/addProblemSubmit" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>题目标题：<input type="text" name="prob_title" /></p>
    <p>题目权限：<input type="radio" name="prob_priv" value="private"/>私有
                 <input type="radio" name="prob_priv" value="protected"/>上级可见
                 <input type="radio" name="prob_priv" value="public"/>全局可见</p>
    <p>时间限制：<input type="text" name="prob_time" /></p>
    <p>内存限制：<input type="text" name="prob_memory" /></p>
    <p>代码长度限制：<input type="text" name="prob_codelength" /></p>
    <p>题目描述：<textarea style="width: 667px; height: 373px" name="prob_desc"></textarea></p>
    <p>是否需要特判：<input type="radio" name="is_spj" value="0"/>否
                     <input type="radio" name="is_spj" value="1"/>是</p>
    <p>上传输入数据：<input type="file" name="file" /></p>
    <p>上传输出数据：<input type="file" name="file" /></p>
    <p><input type="submit" value="submit" /></p>

</form>

{% endblock %}

kari/templates/Problem/old_updateProblem.html
{% extends "base.html" %}

{% block title %} 修改题目 {% endblock %}

{% block main-left %}

<form action="/Problem/updateProblemSubmit/{{ p.pid }}/" method="POST">
    {% csrf_token %}
    <p>题目标题：<input type="text" name="prob_title" value='{{ p.prob_title }}' /></p>
    <p>题目权限：<input type="radio" name="prob_priv" value="private"/>私有
                 <input type="radio" name="prob_priv" value="protected"/>上级可见
                 <input type="radio" name="prob_priv" value="public"/>全局可见</p>
    <p>时间限制：<input type="text" name="prob_time" value='{{ p.prob_time }}'/></p>
    <p>内存限制：<input type="text" name="prob_memory" value='{{ p.prob_memory }}'/></p>
    <p>代码长度限制：<input type="text" name="prob_codelength" value='{{ p.prob_codelength }}' /></p>
    <p>题目描述：<textarea style="width: 667px; height: 373px" name="prob_desc">{{ p.prob_desc }}</textarea></p>
    <p>是否需要特判：<input type="radio" name="is_spj" value="0"/>否
                     <input type="radio" name="is_spj" value="1"/>是</p>
    <p><input type="submit" value="submit" /></p>

</form>

{% endblock %}

kari/templates/Problem/problemList.html
{% extends "base.html" %}

{% block title %} 题目列表 {% endblock %}

{% block main-left %}

{% for p in res %}
<p><a href="{% url 'Problem:problem' p.pid %}">{{ p.pid }} {{ p.prob_title }}</a>
<a href="{% url 'Problem:updateproblem' p.pid %}">修改题目</a>
</p>
{% endfor %}

{% endblock %}

{% block main-right %}
{% endblock %}

kari/templates/Problem/see.html
{% extends "base.html" %}

{% block title %} 添加题目 {% endblock %}

{% block main-left %}
<form action="/Problem/addProblemSubmit" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="提交">
</form>
{% endblock %}

{% block main-right %}
{% endblock %}

kari/templates/Problem/testPage.html
<form enctype="multipart/form-data" method="POST" action="/address/upload/">
    <input type="file" name="file" /><br/>
    <input type="submit" value="上传文件" />
</form>

kari/templates/Problem/testUpload.html
{% extends "base.html" %}

{% block title %} 添加题目 {% endblock %}

{% block main-left %}
<script src="/static/js/problem.js"></script>
<form action="{% url 'Problem:testups' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_table}}
    <input type="submit" value="提交">
</form>
{% endblock %}

{% block main-right %}
{% endblock %}

kari/templates/Problem/updateProblem.html
{% extends "base.html" %}

{% block title %} 修改题目 {% endblock %}

{% block main-left %}
<script src="/static/js/problem.js"></script>
<form action="{% url 'Problem:updatecommit' pid %}" method="POST" enctype="multipart/form-data" onSubmit="return checkAllData()">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <table class="table table-bordered" id="data_table">
        <tr>
            <th width="10%" class="data_modifiy">
                <button type="button" onclick="addData()">添加</button>
            </th>
            <th width="40%" class="data_in">输入数据文件
            </th>
            <th width="40%" class="data_out">输出数据文件
            </th>
            <th width="10%" class="data_scr">数据得分
            </th>
        </tr>
    </table>
    <input type="submit" value="提交">
</form>
{% endblock %}

{% block main-right %}
{% endblock %}