kari/Api/urls.py
from django.conf.urls import patterns, include, url
from Api import views

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^user/(?P<uid>\d+)/?$', views.userDetail ),
    url(r'^group/(?P<gid>\d+)/?$', views.groupDetail ),
    url(r'^login/?$', views.userLogin ),
    url(r'^contest/(?P<cid>\d+)/board/?$', views.boardDetail ),
)

kari/Contest/urls.py
from django.conf.urls import patterns, url
from Contest import views

urlpatterns = patterns('',
        url(r'^$', views.listContestByUser, name='list_available_contests'),
        url(r'^page/(?P<pageId>\d+)/$', views.listContestByUser, name='list_user_contest'),
        url(r'^manage/$', views.listContestByUserAndPriv, name='list_user_contest_manage'),
        url(r'^manage/page/(?P<pageId>\d+)/$', views.listContestByUserAndPriv, name='list_user_contest_manage'),
        url(r'^myself/$', views.listContestByAuthor, name='list_user_contest_myself'),
        url(r'^myself/page/(?P<pageId>\d+)/$', views.listContestByAuthor, name='list_user_contest_myself'),
        url(r'^courseclass/(?P<ccId>\d+)/$', views.listContest, name='list_contest'),
        url(r'^courseclass/(?P<ccId>\d+)/page/(?P<pageId>\d+)/$', views.listContest, name='list_contest'),
        url(r'^manage/courseclass/(?P<ccId>\d+)/$', views.listContestByPriv, name='list_contest_manage'),
        url(r'^manage/courseclass/(?P<ccId>\d+)/page/(?P<pageId>\d+)/$', views.listContestByPriv, name='list_contest_manage'),
        url(r'^(?P<cId>\d+)/$', views.showContest, name='show_contest'),
        url(r'^add/$', views.chooseCourseClass, name='add_contest_choose'), 
        url(r'^add/courseclass/(?P<ccId>\d+)/$', views.addContest, name='add_contest'), 
        url(r'^update/(?P<cId>\d+)/$', views.updateContest, name='update_contest'), 
        url(r'^release_board/(?P<cId>\d+)/$', views.releaseBoardTime, name='release_board'), 
        url(r'^notice/contest/(?P<cId>\d+)/$', views.listContestNotice, name='list_contest_notice'),
        url(r'^(?P<cId>\d+)/notice/(?P<cnId>\d+)/$', views.showContestNotice, name='show_contest_notice'), 
        url(r'^notice/add/contest/(?P<cId>\d+)/$', views.addContestNotice, name='add_contest_notice'), 
        url(r'^notice/update/(?P<cnId>\d+)/contest/(?P<cId>\d+)/$', views.updateContestNotice, name='update_contest_notice'), 
        url(r'^getContestNoticeList/$', views.getContestNoticeList, name='get_contest_notice_list'),

        url(r'^clarifications/(?P<cid>\d+)/$', views.viewAllClarifications, name='view_all_clars'),
        url(r'^clarifications/add/(?P<cid>\d+)/$', views.addClarification, name='add_clar'),
        url(r'^clarifications/answer/(?P<clar_id>\d+)/$', views.answerClarification, name='answer_clar'),
        url(r'^clarifications/delete/(?P<clar_id>\d+)/$', views.deleteClarification, name='delete_clar'),
        url(r'^all/$', views.listContestByUserAll, name='list_all_contests'),

        #url(r'^contestself$', views.listContestByUserSelf),
        )

kari/Submission/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
from Submission import views, general_views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kari.views.home', name='home'),
    # url(r'^kari/', include('kari.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url( r'^$', views.index, name='index'),
    url( r'^(?i)index/$', views.index, name='index'),
    # url( r'^(?i)all/(\d+)/$', views.submissionList, name='all'),
    # url( r'^(?i)all/$', views.submissionList, name='all'),
    # url( r'^(?i)status/$', views.submissionList, name='status'),
    url( r'^(?i)rejudge/in_contest/(?P<sid>\d+)/$', views.rejudgeSubmission, name='contest_rejudge'),
    url( r'^(?i)status/$', general_views.generalSubmissionList, name='status'),
    url( r'^(?i)status/page/(?P<page_id>\d+)/$', general_views.generalSubmissionList, name='status'),
    url( r'^(?i)submit/(?P<problem_id>\d+)/$', general_views.addGeneralSubmission, name='general_submit'),
    url( r'^(?i)submit/$', general_views.addGeneralSubmission, name='general_submit'),
    url( r'^(?i)detail/(?P<gsid>\d+)/$', general_views.viewCodeAndInfo, name='general_code_and_info'),
    url( r'^(?i)rejudge/(\d+)/$', general_views.rejudgeGeneralSubmission, name='general_rejudge'),

    url( r'^status/contest/(?P<contest_id>\d+)/$', views.submissionList, name='contest_status'), # modified
    url( r'^status/contest/(?P<contest_id>\d+)/page/(?P<page_id>\d+)/$', views.submissionList, name='contest_status'), # modified
    url( r'^(?i)submit/contest/(?P<contest_id>\d+)/problem/(?P<problem_index>([A-Z]))/$', views.addSubmission, name='submit'), # modified
    url( r'^(?i)detail/in_contest/(\d+)/$', views.viewCodeAndInfo, name='code_and_info'),
)

kari/kari/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kari.views.home', name='home'),
    # url(r'^kari/', include('kari.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

    #common url
    url( r'^$', 'common.views.index', name='index'),
    url( r'^login/$', 'common.views.login', name='login'),
    url( r'^logout/$', 'common.views.logout', name='logout'),
    url( r'^test/$', 'common.views.test', name='test'),
    url( r'^faq/$', 'common.views.faq', name='faq'),
    url( r'^whitepaper/$', 'common.views.whitepaper', name='whitepaper'),
    url( r'^abouttemp/$', 'common.views.about', name='about'),
    url( r'^register/$', 'common.views.register', name='register'),

    url( r'^contest/', include( 'Contest.urls', namespace='Contest')),
    url( r'^submission/', include( 'Submission.urls', namespace='Submission')),
    #url( r'^submission2/', include( 'Submission2.urls', namespace='Submission2')),
    url( r'^course/', include( 'Course.urls', namespace='Course')),
    url( r'^user/', include( 'User.urls', namespace='User')),
    url( r'^problem/', include( 'Problem.urls', namespace='Problem' )),
    url( r'^statistic/', include( 'Statistic.urls', namespace='Statistic' )),
    #url( r'^statistic2/', include( 'Statistic2.urls', namespace='Statistic2' )),
    url( r'^cheat/', include( 'Cheat.urls', namespace='Cheat' )),

    #url( r'^fresh/', include( 'Fresh.urls', namespace = 'Fresh')),    
    url( r'^apply/', include( 'Register.urls', namespace = 'Register')),    
    url( r'^ckeditor/', include('ckeditor.urls')),

    url( r'^print/', include('Print.urls')),

    url( r'^api/', include('Api.urls')),
)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/',include(debug_toolbar.urls)),
    )

kari/lyy/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
from lyy import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kari.views.home', name='home'),
    # url(r'^kari/', include('kari.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url( r'^$', views.index, name='index'),
    url( r'^index/$', views.index, name='index'),
    url( r'^board/$', views.board, name='board'),
    url( r'^showStudent/$', views.showStudentByCCId, name='showStudent'),
    url( r'^showCourseClass/$', views.showCourseClass, name='showCourseClass'),
)

kari/Contest/forms.py
# -*- coding: utf-8 -*-

from datetime import datetime, date, time, timedelta
from django import forms
from kari.const import Const
from django.forms.extras.widgets import SelectDateWidget
from Contest.widgets import SelectTimeWidget


class contestForm(forms.Form):
    LANG_CHOICE = (
        ('gcc', u'允许提交C代码'), 
        ('g++', u'允许提交C++代码'), 
        ('java', u'允许提交JAVA代码'), 
    )
    CONTEST_CHOICE = (
        ('0', u'公开'),
        ('1', u'私有'),
    )
    BOARD_CHOICE = (
        ('0', u'ACM式'), 
        ('1', u'分组计分式'), 
        ('2', u'仅提交，不判题式')
    )
    STAT_CHOICE = (
        ('0', u'全部信息可见'),
        ('1', u'仅自己的信息可见'),
    )
    title = forms.CharField(max_length=64, min_length=1,
            label=u'测验标题', widget=forms.TextInput(attrs={
                'class':'input-block-level',
                'placeholder':'Contest Title'}))
    desc = forms.CharField(required=False, label=u'测验描述',
            widget=forms.Textarea(attrs={
                'class':'input-block-level',
                'placeholder':'Contest Description'}))
    start_date = forms.DateField(initial=date.today()+timedelta(days=1), label=u'开始日期',
            widget=forms.DateInput(format='%Y-%m-%d', attrs={
                'class':'input-small',
                'placeholder':'YYYY-MM-DD'}))
    start_time = forms.TimeField(initial=time(9, 0, 0),label=u'开始时间',
            widget=forms.TimeInput(format='%H:%M:%S',attrs={
                'class':'input-small',
                'placeholder':'hh:mm:ss'}))
    length = forms.IntegerField(min_value=1, initial=300, label=u'测验时长',
            widget=forms.TextInput(attrs={
                'class':'input-small',
                'placeholder':'Contest Duration'}), )
    board_stop = forms.IntegerField(min_value=1, initial=300, label=u'排行榜时长',
            widget=forms.TextInput(attrs={
                'class':'input-small',
                'placeholder':'Board Duration'}), )
    contest_type = forms.ChoiceField(choices=STAT_CHOICE, label=u'统计信息查看限制')
    board_type = forms.ChoiceField(choices=BOARD_CHOICE, label=u'计分形式')
    lang_limit = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=LANG_CHOICE,
                                           initial=['gcc', 'g++', 'java'], label=u'语言限制')

    started = forms.CharField(widget=forms.HiddenInput(), required=False)
    
    def clean(self):
        cleaned_data = super(contestForm, self).clean()        
        start_date = cleaned_data.get('start_date')
        start_time = cleaned_data.get('start_time')
        length = cleaned_data.get('length')
        started = cleaned_data.get('started')
                
        if start_date and start_time and length:
            if started == 'True':
                if datetime.combine(start_date, start_time) + timedelta(minutes=length) < datetime.now():
                    raise forms.ValidationError(Const.CONTEST_END_TIME_ERR)
            elif datetime.combine(start_date, start_time) < datetime.now():
                raise forms.ValidationError(Const.CONTEST_TIME_ERR)
        
        return cleaned_data
    
class contestNoticeForm(forms.Form):
    title = forms.CharField(max_length=128, min_length=1, label=u'公告标题')
    content = forms.CharField(widget=forms.Textarea, required=False, label=u'公告内容')

class ClarificationForm(forms.Form):
    question = forms.CharField(max_length = 2048)

class AnswerClarificationForm(forms.Form):
    answer = forms.CharField(max_length = 2048)

kari/templates/Contest/addContest.html
{% extends "base.html" %}

{% block title %} 添加考试 {% endblock %}

{% block main-left %}
<script src="/static/js/contest.js"></script>    
<form action="{% url 'Contest:add_contest' ccid %}" method="POST" enctype="multipart/form-data" onSubmit="return checkAllProblem()">
{% csrf_token %}
<table class="table table-bordered">
{{ form.as_table }}
</table>
{% if recent_problem %}
<p><b>最近添加的题目：</b></p>
<div style="width:600px; height:300px; overflow:auto">
<table class="table" id="recent_problem_table">
<tbody>
<tr>
<th width="20%" class="problem_id">题目ID</th>
<th width="60%" class="problem_title">题目标题</th>
<th width="20%">添加</th>
</tr>
{% for p in recent_problem %}
<tr>
<td><class="recent_problem_id" id="recent_problem_id_{{ forloop.counter }}">{{ p.pid }}</td>
<td><class="recent_problem_title" id="recent_problem_title_{{ forloop.counter }}">{{ p.prob_title }}</td>
<td><button type="button" onclick="addRecentProb({{ forloop.counter }})">添加</button></td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
{% endif %}
<table class="table table-bordered" id="problem_table">
<tbody>
<tr>
<th width="10%" class="problem_modify"><button type="button" onclick="addProb()">添加</button></th>
<th width="30%">题目ID</th>
<th width="30%" class="problem_title_custom">自定义标题</th>
<th width="30%" class="problem_title">默认标题</th>
</tr>
{% for p in problem_list %}
<tr id="problem_{{ p.idx }}">
<td class="problem_modify"><button type="button" onclick="delProb({{ p.idx }})">删除</button></td>
<td><input type="text" name="problem_id" id="problem_id_{{ p.idx }}" onchange="checkProblem({{ p.idx }})" value="{{ p.pid }}" autocomplete="off"></td>
<td><input type="text" name="problem_title_custom" id="problem_title_custom_{{ p.idx }}" value="{{ p.title }}"></td>
<td><class="problem_title" id="problem_title_{{ p.idx }}">{{ p.title }}</td>
</tr>
{% endfor %}
</tbody>
</table>
<input type="submit" value="提交">
</form>
{% endblock %}

{% block main-right %}
<p><a href="{% url 'Course:showCourseClass' ccid %}"> 返回课程分班 </a></p>
{% endblock %}

kari/templates/Contest/addContestNotice.html
{% extends "base.html" %}

{% block title %} 添加考试公告 {% endblock %}

{% block main-left %}
<form action="{% url 'Contest:add_contest_notice' cid %}" method="POST" enctype="multipart/form-data">
{% csrf_token %}
<table class="table table-bordered">
{{ form.as_table }}
</table>
<input type="submit" value="提交">
</form>
{% endblock %}

{% block main-right %}
<p><a href="{% url 'Contest:show_contest' cid %}"> 返回考试 </a></p>
<p><a href="{% url 'Contest:list_contest_notice' cid %}"> 考试公告列表 </a></p>
{% endblock %}

kari/templates/Contest/contestList.html
{% extends "Contest/contestListBase.html" %}

{% block title %} 考试列表 {% endblock %}

{% block pagination %}
{% if contest_list.has_previous %}
<a href="{% url 'Contest:list_contest' course_class contest_list.previous_page_number %}" title="Pre">上一页</a>
{% endif %}
{% for p in page_range %}
{% ifequal p contest_list.number %}
<span style="font-size:16px;" title="当前页"><b>{{ p }}</b></span>        
{% else %}
<a href="{% url 'Contest:list_contest' p %}" title="第{{ p }}页">{{ p }}</a>
{% endifequal %}
{% endfor %}     
{% if contest_list.has_next %}
<a href="{% url 'Contest:list_contest' course_class contest_list.previous_page_number %}" title="Next">下一页</a>
 {% endif %}  
{% endblock %}

{% block main-right %}
<p>{% ifequal user.priv "courseclass" %}<a href="{% url 'Course:listCourseClass' %}"> 返回我管理的课程分班列表 </a>{% else %}<a href="{% url 'Course:showCourseClass' course_class.id %}"> 返回课程分班 </a>{% endifequal %}</p>
{% endblock %}

kari/templates/Contest/contestListBase.html
{% extends "base.html" %}

{% block title %} 考试列表 {% endblock %}

{% block main-left %}
<div class="pagination">
{% block pagination %}{% endblock %}
<b>
{%if contest_list.paginator.num_pages %}
共 {{ contest_list.paginator.num_pages }} 页
{% endif %}
</b>
</div>
<table class="table table-striped table-bordered">
<tr>
<th width="10%">考试编号</th>
<th width="35%">名称</th>
<th width="25%">开始时间</th>
<th width="10%">状态</th>
<th width="10%">持续时间</th>
<th width="10%">类型</th>
{% for c in contest_list.object_list %}
<tr>
<td> {{ c.id }} </td>
<td><a href="{% url 'Contest:show_contest' c.id %}"> {{ c.title }} </td>
<td> {{ c.start_time }} </td>
<td> {{ c.status }} </td>
<td> {{ c.length }} </td>
<td> {{ c.type }} </td>
</tr>
{% endfor %}
</table>
{% endblock %}

kari/templates/Contest/contestListByAuthor.html
{% extends "Contest/contestListByPrivBase.html" %}

{% block title %} 考试列表 {% endblock %}

{% block pagination %}
{% if contest_list.has_previous %}
<a href="{% url 'Contest:list_user_contest_myself' course_class contest_list.previous_page_number %}" title="Pre">上一页</a>
{% endif %}
{% for p in page_range %}
{% ifequal p contest_list.number %}
<span style="font-size:16px;" title="当前页"><b>{{ p }}</b></span>        
{% else %}
<a href="{% url 'Contest:list_user_contest_myself' p %}" title="第{{ p }}页">{{ p }}</a>
{% endifequal %}
{% endfor %}     
{% if contest_list.has_next %}
<a href="{% url 'Contest:list_user_contest_myself' course_class contest_list.previous_page_number %}" title="Next">下一页</a>
 {% endif %}  
{% endblock %}

kari/templates/Contest/contestListByPriv.html
{% extends "Contest/contestListByPrivBase.html" %}

{% block title %} 考试列表 {% endblock %}

{% block pagination %}
{% if contest_list.has_previous %}
<a href="{% url 'Contest:list_contest_manage' course_class contest_list.previous_page_number %}" title="Pre">上一页</a>
{% endif %}
{% for p in page_range %}
{% ifequal p contest_list.number %}
<span style="font-size:16px;" title="当前页"><b>{{ p }}</b></span>        
{% else %}
<a href="{% url 'Contest:list_contest_manage' p %}" title="第{{ p }}页">{{ p }}</a>
{% endifequal %}
{% endfor %}     
{% if contest_list.has_next %}
<a href="{% url 'Contest:list_contest_manage' course_class contest_list.previous_page_number %}" title="Next">下一页</a>
 {% endif %}  
{% endblock %}

{% block main-right %}
<p><a href="{% url 'Contest:add_contest' course_class.id %}"> 添加考试 </a></p>
<p>{% ifequal user.priv "courseclass" %}<a href="{% url 'Course:listCourseClass' %}"> 返回我管理的课程分班列表 </a>{% else %}<a href="{% url 'Course:showCourseClass' course_class.id %}"> 返回课程分班 </a>{% endifequal %}</p>
{% endblock %}

kari/templates/Contest/contestListByPrivBase.html
{% extends "base.html" %}

{% block title %} 考试列表 {% endblock %}

{% block main-left %}
<div class="pagination">
{% block pagination %}{% endblock %}
<b>
{%if contest_list.paginator.num_pages %}
共 {{ contest_list.paginator.num_pages }} 页
{% endif %}
</b>
</div>
<table class="table table-striped table-bordered">
<tr>
<th width="10%">考试编号</th>
<th width="30%">名称</th>
<th width="20%">开始时间</th>
<th width="10%">状态</th>
<th width="10%">持续时间</th>
<th width="10%">类型</th>
<th width="10%">修改考试</th>
{% for c in contest_list.object_list %}
<tr>
<td> {{ c.id }} </td>
<td><a href="{% url 'Contest:show_contest' c.id %}"> {{ c.title }} </td>
<td> {{ c.start_time }} </td>
<td> {{ c.status }} </td>
<td> {{ c.length }} </td>
<td> {{ c.type }} </td>
<td><a href="{% url 'Contest:update_contest' c.id %}"> 修改考试 </td>
</tr>
{% endfor %}
</table>
{% endblock %}

kari/templates/Contest/contestListByUser.html
{% extends "Contest/contestListBase.html" %}

{% block title %} 考试列表 {% endblock %}

{% block pagination %}
{% if contest_list.has_previous %}
<a href="{% url 'Contest:list_user_contest' course_class contest_list.previous_page_number %}" title="Pre">上一页</a>
{% endif %}
{% for p in page_range %}
{% ifequal p contest_list.number %}
<span style="font-size:16px;" title="当前页"><b>{{ p }}</b></span>        
{% else %}
<a href="{% url 'Contest:list_user_contest' p %}" title="第{{ p }}页">{{ p }}</a>
{% endifequal %}
{% endfor %}     
{% if contest_list.has_next %}
<a href="{% url 'Contest:list_user_contest' course_class contest_list.previous_page_number %}" title="Next">下一页</a>
 {% endif %}  
{% endblock %}

kari/templates/Contest/contestListByUserAndPriv.html
{% extends "Contest/contestListByPrivBase.html" %}

{% block title %} 考试列表 {% endblock %}

{% block pagination %}
{% if contest_list.has_previous %}
<a href="{% url 'Contest:list_user_contest_manage' course_class contest_list.previous_page_number %}" title="Pre">上一页</a>
{% endif %}
{% for p in page_range %}
{% ifequal p contest_list.number %}
<span style="font-size:16px;" title="当前页"><b>{{ p }}</b></span>        
{% else %}
<a href="{% url 'Contest:list_user_contest_manage' p %}" title="第{{ p }}页">{{ p }}</a>
{% endifequal %}
{% endfor %}     
{% if contest_list.has_next %}
<a href="{% url 'Contest:list_user_contest_manage' course_class contest_list.previous_page_number %}" title="Next">下一页</a>
 {% endif %}  
{% endblock %}

kari/templates/Contest/contestNoticeList.html
{% extends "base.html" %}

{% block title %} 考试公告列表 {% endblock %}

{% block main-left %}
<table class="table table-striped table-bordered">
<tr>
<th width="10%">公告编号</th>
<th width="80%">名称</th>
{% if has_priv %}
<th width="10%">修改公告</th>
{% endif %}
{% for cn in contest_notice_list %}
<tr>
<td> {{ cn.id }} </td>
<td><a href="{% url 'Contest:show_contest_notice' cid cn.id %}"> {{ cn.notice_title }} </td>
{% if has_priv %}
<td><a href="{% url 'Contest:update_contest_notice' cid cn.id %}"> 修改公告 </td>
{% endif %}
</tr>
{% endfor %}
</table>
{% endblock %}

{% block main-right %}
<p><a href="{% url 'Contest:show_contest' cid %}"> 返回考试 </a></p>
{% if has_priv %}
<p><a href="{% url 'Contest:add_contest_notice' cid %}"> 添加考试公告 </a></p>
{% endif %}
{% endblock %}

kari/templates/Contest/showContest.html
{% extends "base.html" %}

{% block title %} 考试信息 {% endblock %}

{% block main-left %}
<script> var cid = {{ contest.cid }} </script>
<script src="/static/js/contest.js"></script>    
<b> 考试公告：</b>
<marquee id="contest_notice"  onmouseover="stop();"  onmouseout="start();"></marquee>
<h2> {{ contest.title }} </h2>
<p> {{ contest.now }} {{ contest.start_time }} {{ contest.status }} {{ contest.left }} </p>
<table class="table table-striped table-bodered">
<tr>
<th width="10%">已通过</th>
<th width="10%">题目ID</th>
<th width="50%">题目标题</th>
<th width="10%">通过数</th>
<th width="10%">提交数</th>
<th width="10%">通过比例</th>
</tr>
{% for p in problem_list %}
<tr>
<td></td>
<td><a href="{% url 'Problem:contestproblem' contest.cid p.index %}"> {{ p.index }}</a></td>
<td><a href="{% url 'Problem:contestproblem' contest.cid p.index %}"> {{ p.title }}</a></td>
<td></td>
<td></td>
<td></td>
</tr>
{% endfor %}
</table>
{% endblock %}

{% block main-right %}
<p><a href="{% url 'Course:showCourseClass' ccid %}"> 返回课程分班 </a></p>
<p><a href="{% url 'Contest:list_contest_notice' contest.cid %}"> 考试公告列表 </a></p>
<p><a href="{% url 'Submission:contest_status' contest.cid %}"> 考试提交列表 </a></p>
{% if has_priv %}
<p><a href="{% url 'Contest:update_contest' contest.cid %}"> 修改考试 </a></p>
<p><a href="{% url 'Contest:add_contest_notice' contest.cid %}"> 添加考试公告 </a></p>
{% endif %}
{% endblock %}

kari/templates/Contest/showContestNotice.html
{% extends "base.html" %}

{% block title %} 考试公告 {% endblock %}

{% block main-left %}
<h2> {{ contest_notice.notice_title }} </h2>
<p> {{ contest_notice.notice_content }} </p>
{% endblock %}

{% block main-right %}
<p><a href="{% url 'Contest:show_contest' cid %}"> 返回考试 </a></p>
<p><a href="{% url 'Contest:list_contest_notice' cid %}"> 考试公告列表 </a></p>
{% if has_priv %}
<p><a href="{% url 'Contest:update_contest_notice' contest_notice.id cid %}"> 修改考试公告 </a></p>
{% endif %}
{% endblock %}

kari/templates/Contest/updateContest.html
{% extends "base.html" %}

{% block title %} 修改考试 {% endblock %}

{% block main-left %}
<script src="/static/js/contest.js"></script>    
<form action="{% url 'Contest:update_contest' cid %}" method="POST" enctype="multipart/form-data" onSubmit="return checkAllProblem()">
{% csrf_token %}
<table class="table table-bordered">
{{ form.as_table }}
</table>
<table class="table table-bordered" id="problem_table">
<tbody>
<tr>
<th width="10%" class="problem_modify"><button type="button" onclick="addProb()" {% if started %} disabled {% endif %}>添加</button></th>
<th width="30%">题目ID</th>
<th width="30%" class="problem_title_custom">自定义标题</th>
<th width="30%" class="problem_title">默认标题</th>
</tr>
{% for p in problem_list %}
<tr id="problem_{{ p.idx }}">
<td class="problem_modify"><button type="button" onclick="delProb({{ p.idx }})" {% if started %} disabled {% endif %}>删除</button></td>
<td><input type="text" name="problem_id" id="problem_id_{{ p.idx }}" onchange="checkProblem({{ p.idx }})" value="{{ p.pid }}" autocomplete="off" {% if started %} readonly {% endif %}></td>
<td><input type="text" name="problem_title_custom" id="problem_title_custom_{{ p.idx }}" value="{{ p.title }}"></td>
<td><class="problem_title" id="problem_title_{{ p.idx }}">{{ p.title }}</td>
</tr>
{% endfor %}
</tbody>
</table>
<input type="submit" value="提交">
</form>
{% endblock %}

{% block main-right %}
<p><a href="{% url 'Contest:show_contest' cid %}"> 返回考试 </a></p>
<p><a href="{% url 'Contest:list_contest' ccid 1 %}"> 考试列表 </a></p>
{% endblock %}

kari/templates/Contest/updateContestNotice.html
{% extends "base.html" %}

{% block title %} 修改考试公告 {% endblock %}

{% block main-left %}
<form action="{% url 'Contest:update_contest_notice' cnid cid %}" method="POST" enctype="multipart/form-data">
{% csrf_token %}
<table class="table table-bordered">
{{ form.as_table }}
</table>
<input type="submit" value="提交">
</form>
{% endblock %}

{% block main-right %}
<p><a href="{% url 'Contest:show_contest' cid %}"> 返回考试 </a></p>
<p><a href="{% url 'Contest:show_contest_notice' cid cnid %}"> 返回考试公告 </a></p>
<p><a href="{% url 'Contest:list_contest_notice' cid %}"> 考试公告列表 </a></p>
{% endblock %}