kari/Api/urls.py
from django.conf.urls import patterns, include, url
from Api import views

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^user/(?P<uid>\d+)/?$', views.userDetail ),
    url(r'^group/(?P<gid>\d+)/?$', views.groupDetail ),
    url(r'^login/?$', views.userLogin ),
    url(r'^contest/(?P<cid>\d+)/board/?$', views.boardDetail ),
)

kari/Contest/urls.py
from django.conf.urls import patterns, url
from Contest import views

urlpatterns = patterns('',
        url(r'^$', views.listContestByUser, name='list_available_contests'),
        url(r'^page/(?P<pageId>\d+)/$', views.listContestByUser, name='list_user_contest'),
        url(r'^manage/$', views.listContestByUserAndPriv, name='list_user_contest_manage'),
        url(r'^manage/page/(?P<pageId>\d+)/$', views.listContestByUserAndPriv, name='list_user_contest_manage'),
        url(r'^myself/$', views.listContestByAuthor, name='list_user_contest_myself'),
        url(r'^myself/page/(?P<pageId>\d+)/$', views.listContestByAuthor, name='list_user_contest_myself'),
        url(r'^courseclass/(?P<ccId>\d+)/$', views.listContest, name='list_contest'),
        url(r'^courseclass/(?P<ccId>\d+)/page/(?P<pageId>\d+)/$', views.listContest, name='list_contest'),
        url(r'^manage/courseclass/(?P<ccId>\d+)/$', views.listContestByPriv, name='list_contest_manage'),
        url(r'^manage/courseclass/(?P<ccId>\d+)/page/(?P<pageId>\d+)/$', views.listContestByPriv, name='list_contest_manage'),
        url(r'^(?P<cId>\d+)/$', views.showContest, name='show_contest'),
        url(r'^add/$', views.chooseCourseClass, name='add_contest_choose'), 
        url(r'^add/courseclass/(?P<ccId>\d+)/$', views.addContest, name='add_contest'), 
        url(r'^update/(?P<cId>\d+)/$', views.updateContest, name='update_contest'), 
        url(r'^release_board/(?P<cId>\d+)/$', views.releaseBoardTime, name='release_board'), 
        url(r'^notice/contest/(?P<cId>\d+)/$', views.listContestNotice, name='list_contest_notice'),
        url(r'^(?P<cId>\d+)/notice/(?P<cnId>\d+)/$', views.showContestNotice, name='show_contest_notice'), 
        url(r'^notice/add/contest/(?P<cId>\d+)/$', views.addContestNotice, name='add_contest_notice'), 
        url(r'^notice/update/(?P<cnId>\d+)/contest/(?P<cId>\d+)/$', views.updateContestNotice, name='update_contest_notice'), 
        url(r'^getContestNoticeList/$', views.getContestNoticeList, name='get_contest_notice_list'),

        url(r'^clarifications/(?P<cid>\d+)/$', views.viewAllClarifications, name='view_all_clars'),
        url(r'^clarifications/add/(?P<cid>\d+)/$', views.addClarification, name='add_clar'),
        url(r'^clarifications/answer/(?P<clar_id>\d+)/$', views.answerClarification, name='answer_clar'),
        url(r'^clarifications/delete/(?P<clar_id>\d+)/$', views.deleteClarification, name='delete_clar'),
        url(r'^all/$', views.listContestByUserAll, name='list_all_contests'),

        #url(r'^contestself$', views.listContestByUserSelf),
        )

kari/Course/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
from Course import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kari.views.home', name='home'),
    # url(r'^kari/', include('kari.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    #url( r'^$', views.index, name='index'),
    #url( r'^index/$', views.index, name='index'),
    url( r'^(?P<course_id>\d+)/$', views.showCourse, name='showCourse'),
    url( r'^add/$', views.addCourse, name='addCourse'),
    url( r'^add/school/(?P<school_id>\d+)/$', views.addCourse, name='addCourse'),
    url( r'^update/(?P<course_id>\d+)/$', views.updateCourse, name='updateCourse'),
    # url( r'^delete/(?P<course_id>\d+)/$', views.deleteCourse, name='deleteCourse'),
    url( r'^setadmin/c/(?P<course_id>\d+)/$', views.setCourseAdmin, name='setCourseAdmin'),

    url( r'^list/school/(?P<school_id>\d+)/$', views.courseList, name='listCourse'),

    url( r'^courses/$', views.courseList, name='courses'),
    url( r'^courses/page/(?P<page_id>\d+)/$', views.courseList, name='courses'),
    url( r'^(?P<course_id>\d+)/problems/$', views.showCourseProblems, name='courseProblems'),
    url( r'^(?P<course_id>\d+)/problems/page/(?P<page_id>\d+)/$', views.showCourseProblems, name='courseProblems'),
    url( r'^(?P<course_id>\d+)/classes/$', views.showCourseClasses, name='courseClasses'),
    url( r'^(?P<course_id>\d+)/classes/page/(?P<page_id>\d+)/$', views.showCourseClasses, name='courseClasses'),

    url( r'^class/(?P<course_class_id>\d+)/$', views.showCourseClass, name='showCourseClass'),
    url( r'^class/add/$', views.addCourseClass, name='addCourseClass'),
    url( r'^class/add/course/(?P<course_id>\d+)/$', views.addCourseClass, name='addCourseClass'),
    url( r'^class/update/(?P<course_class_id>\d+)/$', views.updateCourseClass, name='updateCourseClass'),
    # url( r'^class/delete/(?P<course_class_id>\d+)/$', views.deleteCourseClass, name='deleteCourseClass'),
    url( r'^setadmin/cc/(?P<course_class_id>\d+)/$', views.setCourseClassAdmin, name='setCourseClassAdmin'),
    # url( r'^classes/course/(?P<course_id>\d+)/$', views.courseClassList, name='listCourseClass'),

    url( r'^classes/$', views.courseClassList, name='classes'),
    url( r'^classes/page/(?P<page_id>\d+)/$', views.courseClassList, name='classes'),
    url( r'^class/(?P<course_class_id>\d+)/groups/add/(?P<group_id>\d+)/$', views.addGroup, name='addGroup'),
    url( r'^class/(?P<course_class_id>\d+)/groups/add/$', views.addGroup, name='addGroup'),
    url( r'^class/(?P<course_class_id>\d+)/groups/$', views.showCourseClassGroups, name='groups'),
    url( r'^class/(?P<course_class_id>\d+)/contests/$', views.showCourseClassContests, name='showCourseClassContests'),
    url( r'^class/(?P<course_class_id>\d+)/students/$', views.showCourseClassStudents, name='students'),
    url( r'^class/(?P<course_class_id>\d+)/problems/$', views.showCourseClassProblems, name='showCourseClassProblems'),

    url( r'^class/(?P<course_class_id>\d+)/groups/page/(?P<page_id>\d+)/$', views.showCourseClassGroups, name='groups'),
    url( r'^class/(?P<course_class_id>\d+)/contests/page/(?P<page_id>\d+)/$', views.showCourseClassContests, name='showCourseClassContests'),
    url( r'^class/(?P<course_class_id>\d+)/students/page/(?P<page_id>\d+)/$', views.showCourseClassStudents, name='students'),
    url( r'^class/(?P<course_class_id>\d+)/problems/page/(?P<page_id>\d+)/$', views.showCourseClassProblems, name='showCourseClassProblems'),
)

kari/User/urls.py
from django.conf.urls import patterns, url
from User import views

urlpatterns = patterns('',
    url(r'^$', views.showUserInfo, name='showinfo'),
    url(r'^update/$', views.update, name='update'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^add/student/$', views.addMultiUser, name='addstudent'),
    url(r'^add/admin/$', views.addAdmin, name='addadmin'),
    url(r'^add/school/$', views.addSchool, name='addschool'),
    url(r'^add/group/$', views.addGroup, name='addgroup'),
    url(r'^viewuser/(?P<uid>\d+)/$', views.viewUserInfo, name='viewuser'),
    url(r'^reset/(?P<uid>\d+)$', views.ResetPasswd, name='reset'),
    url(r'^school/(?P<school_id>\d+)/$', views.showSchool, name='show_school'),
    url(r'^school/(?P<school_id>\d+)/page/(?P<page_id>\d+)/$', views.showSchool, name='show_school'),
    url(r'^manage/admin/$', views.listAdmin, name='manageadmin'),
    url(r'^manage/student/$', views.listStudent, name='managestudent'),
    url(r'^manage/student2/$', views.listStudent2, name='managestudent'),
    url(r'^manage/student/page/(?P<page_id>\d+)/$', views.listStudent, name='managestudent'),
    url(r'^manage/student/page/(?P<page_id>\d+)/$', views.listStudent2, name='managestudent'),
    url(r'^manage/school/$', views.manageSchool, name='manageschool'),
    url(r'^manage/group/$', views.manageGroup, name='managegroup'),
    url(r'^manage/group/page/(?P<pageId>\d+)/$', views.manageGroup, name='managegroup'),
   
    url(r'^modify/school/(?P<school_id>\d+)$', views.modifySchool, name='modifyschool'),
    url(r'^modify/group/(?P<group_id>\d+)$', views.modifyGroup, name='modifygroup'),
    url(r'^modify/group/(?P<group_id>\d+)/resetall/$', views.resetGroupMemberPasswdHomepage, name='resetgrouphomepage'),
    url(r'^modify/group/(?P<group_id>\d+)/resetall/(?P<mode>[a-z]+)$', views.resetGroupMemberPasswd, name='resetgroup'),
    url(r'^modify/group/(?P<group_id>\d+)/delmember/(?P<user_id>\d+)$', views.delMember, name='delgroupmember'),
    url(r'^modify/group/(?P<group_id>\d+)/addmember/$', views.addMember, name='addgroupmember'),
    url(r'^download/(?P<usname>.+)/$',views.csvDownload,name='csvdownload'),
)

kari/kari/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kari.views.home', name='home'),
    # url(r'^kari/', include('kari.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

    #common url
    url( r'^$', 'common.views.index', name='index'),
    url( r'^login/$', 'common.views.login', name='login'),
    url( r'^logout/$', 'common.views.logout', name='logout'),
    url( r'^test/$', 'common.views.test', name='test'),
    url( r'^faq/$', 'common.views.faq', name='faq'),
    url( r'^whitepaper/$', 'common.views.whitepaper', name='whitepaper'),
    url( r'^abouttemp/$', 'common.views.about', name='about'),
    url( r'^register/$', 'common.views.register', name='register'),

    url( r'^contest/', include( 'Contest.urls', namespace='Contest')),
    url( r'^submission/', include( 'Submission.urls', namespace='Submission')),
    #url( r'^submission2/', include( 'Submission2.urls', namespace='Submission2')),
    url( r'^course/', include( 'Course.urls', namespace='Course')),
    url( r'^user/', include( 'User.urls', namespace='User')),
    url( r'^problem/', include( 'Problem.urls', namespace='Problem' )),
    url( r'^statistic/', include( 'Statistic.urls', namespace='Statistic' )),
    #url( r'^statistic2/', include( 'Statistic2.urls', namespace='Statistic2' )),
    url( r'^cheat/', include( 'Cheat.urls', namespace='Cheat' )),

    #url( r'^fresh/', include( 'Fresh.urls', namespace = 'Fresh')),    
    url( r'^apply/', include( 'Register.urls', namespace = 'Register')),    
    url( r'^ckeditor/', include('ckeditor.urls')),

    url( r'^print/', include('Print.urls')),

    url( r'^api/', include('Api.urls')),
)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/',include(debug_toolbar.urls)),
    )

kari/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>{% block title %}{% endblock %}</title>
        <link href="/static/css/home.css" rel="stylesheet" type="text/css"/>
        <link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css"/>
        <script src="/static/js/jquery.js"></script>    
        <script src="/static/js/bootstrap.js"></script>    
        <script src="/static/js/ajaxSetup.js"></script>    
        <style type="text/css">
            .dropdown{
                width: 150px;
                text-align:center; 
            }
        </style>    
    </head>

    <body>
        <div id="main">
            <div id="main-header">
                <div class="bs-docs-example" style="position: relative; top: 100px; left:100px;">
                    <ul class="nav nav-pills">
                        <li><button class="btn" onclick="javascript:window.location.href='/'" style="position : relative; top: 2px; width : 150px; height: 32px; text-align: center;">主页</button></li>
                        <li class="dropdown" style="postion:relative; left:1px;">
                        <a class="btn dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#">Online Judge<b class="caret"></b></a>
                        <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4">
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">常见问题</a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">新闻及公告</a></li>
                        </ul>
                        </li>
                        <li class="dropdown">
                        <a class="btn dropdown-toggle" id="drop5" role="button" data-toggle="dropdown" href="#">题目<b class="caret"></b></a>
                        <ul id="menu2" class="dropdown-menu" role="menu" aria-labelledby="drop5">
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="/problem/list/1">题目列表</a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="/submission/submit/p/1">提交题目</a></li>
                        </ul>
                        </li>
                        <li class="dropdown">
                        <a class="btn dropdown-toggle" id="drop5" role="button" data-toggle="dropdown" href="#">统计分析<b class="caret"></b></a>
                        <ul id="menu2" class="dropdown-menu" role="menu" aria-labelledby="drop5">
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">用户排名</a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="/submission/status">提交状态</a></li>
                        </ul>
                        </li>
                        <li class="dropdown">
                        <a class="btn dropdown-toggle" id="drop5" role="button" data-toggle="dropdown" href="#">考试<b class="caret"></b></a>
                        <ul id="menu2" class="dropdown-menu" role="menu" aria-labelledby="drop5">
                            {% ifequal user.priv 'student' %}
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'Contest:list_user_contest' 1 %}">我能参加的考试列表</a></li>
                            {% else %}
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'Contest:list_user_contest_myself' 1 %}">我创建的考试列表</a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'Contest:list_user_contest_manage' 1 %}">我管理的考试列表</a></li>
                            {% endifequal %}
                        </ul>
                        </li>
                        <li class="dropdown">
                        <a class="btn dropdown-toggle" id="drop5" role="button" data-toggle="dropdown" href="#">课程<b class="caret"></b></a>
                        <ul id="menu2" class="dropdown-menu" role="menu" aria-labelledby="drop5">
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="{% ifequal user.priv "school" %}{% url 'User:show_school' 1 %}{% else %}{% url 'User:show_school' 1 %}{% endifequal %}">课程列表</a></li>
                        </ul>
                        </li>
                    </ul> <!-- /tabs -->
                </div> 
            </div>   
            <div id="main-body">
                <div id="main-left">{% block main-left %}{% endblock %}</div>
                <div id="main-right">
                    {% if user.username %}
                    用户名:{{ user.username }}
                    {% endif %}
                    {% if user.username %}
                    <p><a href="{% url 'User:showinfo' %}">查看个人信息</a></p>
                    <p><a href="{% url 'User:update' %}">更新个人信息</a></p>
                    {% ifequal user.priv 'university' %}
                    <p><a href="{% url 'User:managestudent' %}">管理学生</a><p>
                    <p><a href="{% url 'User:manageadmin' %}">管理管理员</a><p>
                    <p><a href="{% url 'User:manageschool' %}">管理学院</a></p>
                    <p><a href="{% url 'User:managegroup' %}">管理群组</a></p>
                    {% else %}
                    {% ifequal user.priv 'school' %}
                    学院管理员相关链接 
                    <p><a href="{% url 'User:listSchool' %}">我所管理的学院</a></p>
                    {% else %}    
                    {% ifequal user.priv 'course' %}
                    课程管理员相关链接
                    <p><a href="{% url 'Course:listCourse' %}">我所管理的课程</a></p>
                    {% else %}    
                    {% ifequal user.priv 'courseclass' %}
                    课程分班管理员相关链接
                    <p><a href="{% url 'Course:listCourseClass' %}">我所管理的课程分班</a></p>
                    {% else %}    
                    {% ifequal user.priv 'student' %}
                    学生相关链接    
                    <p><a href="{% url 'Course:listCourseClass' %}">我所在的课程分班</a></p>
                    {% endifequal %}
                    {% endifequal %}
                    {% endifequal %}
                    {% endifequal %}
                    {% endifequal %}
                    <p><a href="/user/logout">注销</a></p>
                    {% else %}
                    <p><a href="/user/login">登录</a></p>
                    {% endif %}

                    <br/> <br/>
                    {% block main-right %}{% endblock %}
                </div>
                <div style="clear: both;"></div>
            </div>

            <div id="footer">footer</div>
        </div>
    </body>
</html>

kari/templates/error.html
{% extends "newtpl/base.html" %}

{% block title %} 出错啦！ {% endblock %}

{% block main-left %}
<h1>出错啦！</h1>
<p> {{ errmsg }} </p>

{% endblock %}

{% block main-right %}
{% endblock %}